### ISSUE TITLE
Theme in the screenshot?

### ISSUE THREAD

**Issue by anarchylimes** [embark-theme/iterm#2]
Hey guys! Great work on getting the theme to iTerm2. Looks awesome. Quick question, do you happen to have the shell theme or configuration for whatever theme that is in the screenshots? I would love to use that along side the embark colour scheme. 

Thanks in advance!

**Comment by unknowledgeable** [comment]
Hey @anarchylimes, the theme is [powerlevel10k](https://github.com/romkatv/powerlevel10k) with a few custom colors set after going throught the configurator `p10k configure`

My dotfiles are pretty horrendous and the .p10k.zsh config file for the theme is 1500 lines but the config should be pretty self-explanatory when you run through it. Most important things to make it match mine are:

* Lean style
* 16 color
* Connecting line
* Few icons
